# -*- coding: utf-8 -*-
"""gerador_testes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qek-2RieOQX8iRqH3dfuopliGvDXMlL
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta


lat_base, lon_base = -23.7834, -45.6206
num_pontos = 50

data_inicio = datetime(2026, 6, 23, 8, 0, 0)
pontos = []

for i in range(num_pontos):

    lat = lat_base + np.random.uniform(-0.02, 0.02)
    lon = lon_base + np.random.uniform(-0.02, 0.02)


    lat_raw = int(lat * 10000000)
    lon_raw = int(lon * 10000000)

    hora_atual = data_inicio + timedelta(minutes=i * 20)

    pontos.append({
        'Data': hora_atual.strftime('%d/%m/%Y'),
        'Hora Inicial': hora_atual.strftime('%H:%M:%S'),
        'Latitude': lat_raw,
        'Longitude': lon_raw
    })


df_ficticio = pd.DataFrame(pontos)
df_ficticio.to_excel('dados_investigacao_ficticios.xlsx', index=False)

print("Arquivo 'dados_investigacao_ficticios.xlsx' gerado com sucesso!")