# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146V61MhFP015bpcrDTm0YFHfWQLok686
"""

import pandas as pd
import folium
import base64
import os
import io
from folium.plugins import HeatMap, MiniMap, Draw, Geocoder
from google.colab import files


def get_base64_png(file_path):
    """Converte arquivo PNG em string Base64 para embutir no HTML."""
    if os.path.exists(file_path):
        with open(file_path, "rb") as f:
            encoded = base64.b64encode(f.read()).decode()
        return f"data:image/png;base64,{encoded}"
    return None


try:
    print("1. Selecione o arquivo EXCEL da operadora:")
    uploaded_excel = files.upload()
    file_name_excel = next(iter(uploaded_excel))


    df = pd.read_excel(io.BytesIO(uploaded_excel[file_name_excel]))


    df['Latitude'] = df['Latitude'] / 10000000
    df['Longitude'] = df['Longitude'] / 10000000

    print(f"✅ Arquivo {file_name_excel} processado com sucesso!")


    print("\n2. Carregando ícones da pasta 'sample_data'...")


    icon_viatura_b64 = get_base64_png(os.path.join('sample_data', 'policia.png'))
    if not icon_viatura_b64: print(f"⚠️ Aviso: Ícone policia.png não foi carregado corretamente ou está faltando em sample_data.")

    icon_antena_b64 = get_base64_png(os.path.join('sample_data', 'antena.png'))
    if not icon_antena_b64: print(f"⚠️ Aviso: Ícone antena.png não foi carregado corretamente ou está faltando em sample_data.")

    icon_crime_b64 = get_base64_png(os.path.join('sample_data', 'local_crime.png'))
    if not icon_crime_b64: print(f"⚠️ Aviso: Ícone local_crime.png não foi carregado corretamente ou está faltando em sample_data.")

    icon_hospital_b64 = get_base64_png(os.path.join('sample_data', 'hospital.png'))
    if not icon_hospital_b64: print(f"⚠️ Aviso: Ícone hospital.png não foi carregado corretamente ou está faltando em sample_data.")

    icon_base_b64 = get_base64_png(os.path.join('sample_data', 'base.png'))
    if not icon_base_b64: print(f"⚠️ Aviso: Ícone base.png não foi carregado corretamente ou está faltando em sample_data.")



    centro_inicial = [df['Latitude'].iloc[0], df['Longitude'].iloc[0]]


    mapa = folium.Map(
        location=centro_inicial,
        zoom_start=14,
        control_scale=True,
        tiles='CartoDB positron'
    )


    titulo_html = f'''
        <h1 align="center" style="font-family:verdana; font-size:16px; font-weight:bold;
        background-color:darkblue; color:white; padding:10px; border-radius:10px;">
        ANÁLISE GEOGRÁFICA LBS: {file_name_excel}
        </h1>
    '''
    mapa.get_root().html.add_child(folium.Element(titulo_html))


    coordenadas_calor = []

    for i, row in df.iterrows():
        popup_info = f"<b>Registro:</b> {i+1}<br><b>Data:</b> {row['Data']}<br><b>Hora:</b> {row['Hora Inicial']}"
        lat, lon = row['Latitude'], row['Longitude']
        coordenadas_calor.append([lat, lon])


        # Alterado para usar um marcador padrão (ponto) para o caminho dos infratores
        # A cor vermelha é usada para destacar o percurso, como um 'crime' no mapa.
        folium.Marker(
            location=[lat, lon],
            popup=folium.Popup(popup_info, max_width=300),
            icon=folium.Icon(color='red') # Marcador padrão vermelho para o percurso do infrator
        ).add_to(mapa)


    if icon_crime_b64:
        folium.Marker(
            location=[df['Latitude'].iloc[0] + 0.003, df['Longitude'].iloc[0] + 0.003],
            popup="CENA DO CRIME",
            icon=folium.CustomIcon(icon_crime_b64, icon_size=(45, 45))
        ).add_to(mapa)

    if icon_antena_b64:
        folium.Marker(
            location=[df['Latitude'].iloc[0] - 0.002, df['Longitude'].iloc[0] - 0.002],
            popup="TORRE ERB (OPERADORA)",
            icon=folium.CustomIcon(icon_antena_b64, icon_size=(45, 45))
        ).add_to(mapa)

    # Adicionando marcadores para hospital e base
    if icon_hospital_b64:
        folium.Marker(
            location=[df['Latitude'].iloc[0] + 0.001, df['Longitude'].iloc[0] - 0.003], # Posição ajustada
            popup="HOSPITAL",
            icon=folium.CustomIcon(icon_hospital_b64, icon_size=(45, 45))
        ).add_to(mapa)

    if icon_base_b64:
        folium.Marker(
            location=[df['Latitude'].iloc[0] - 0.001, df['Longitude'].iloc[0] + 0.004], # Posição ajustada
            popup="BASE DA POLÍCIA",
            icon=folium.CustomIcon(icon_base_b64, icon_size=(45, 45))
        ).add_to(mapa)


    HeatMap(coordenadas_calor, radius=15, blur=10, name="Mancha de Calor").add_to(mapa)
    MiniMap().add_to(mapa)
    Draw(export=True).add_to(mapa)
    Geocoder().add_to(mapa)
    folium.LayerControl().add_to(mapa)


    mapa.save('Relatorio_Investigacao_Geografica.html')
    print("\n✅ Mapa gerado com sucesso! Arquivo salvo como: Relatorio_Investigacao_Geografica.html")
    display(mapa)

except Exception as e:
    print(f"\n❌ Erro durante a execução: {e}")
    print("Verifique se as colunas 'Latitude', 'Longitude', 'Data' e 'Hora Inicial' existem no Excel.")